// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZBnSgUxPVlc9IE9SHY78jY29b3IbEYT0',
    appId: '1:203811495171:web:798579faf688f25e28dd36',
    messagingSenderId: '203811495171',
    projectId: 'stepsync-21a5d',
    authDomain: 'stepsync-21a5d.firebaseapp.com',
    storageBucket: 'stepsync-21a5d.firebasestorage.app',
    measurementId: 'G-FHTGRPQKLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVRRz6LEzyioX-FSw_pMkSpXfXNqXkBoc',
    appId: '1:203811495171:android:f74c3cc4def4be0d28dd36',
    messagingSenderId: '203811495171',
    projectId: 'stepsync-21a5d',
    storageBucket: 'stepsync-21a5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMeAen1xv-svmeDeCuKeebGT0U1C11qQQ',
    appId: '1:203811495171:ios:0ac57a483806255828dd36',
    messagingSenderId: '203811495171',
    projectId: 'stepsync-21a5d',
    storageBucket: 'stepsync-21a5d.firebasestorage.app',
    iosClientId: '203811495171-gi3dh8978poae4dcj9knllom2192g8ri.apps.googleusercontent.com',
    iosBundleId: 'com.stepsync.stepSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZBnSgUxPVlc9IE9SHY78jY29b3IbEYT0',
    appId: '1:203811495171:web:7709cfd99f621f4b28dd36',
    messagingSenderId: '203811495171',
    projectId: 'stepsync-21a5d',
    authDomain: 'stepsync-21a5d.firebaseapp.com',
    storageBucket: 'stepsync-21a5d.firebasestorage.app',
    measurementId: 'G-0LZ17EF9BS',
  );
}
